// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPqCIJeISpHtrI0LioVrORxh9HwltJtl8',
    appId: '1:540328794600:web:3e530b4b8c608c65c56c5d',
    messagingSenderId: '540328794600',
    projectId: 'ukruzwa-c52e5',
    authDomain: 'ukruzwa-c52e5.firebaseapp.com',
    storageBucket: 'ukruzwa-c52e5.firebasestorage.app',
    measurementId: 'G-K1YWPV81K6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvi-AzNXViV4CNykg32a9bNVJ-RfTuyHE',
    appId: '1:540328794600:android:e75df6677e8b59f4c56c5d',
    messagingSenderId: '540328794600',
    projectId: 'ukruzwa-c52e5',
    storageBucket: 'ukruzwa-c52e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuhd4OAYWfJWVrnDgikaQX2SrFPodYOuY',
    appId: '1:540328794600:ios:82a5db7d4304d578c56c5d',
    messagingSenderId: '540328794600',
    projectId: 'ukruzwa-c52e5',
    storageBucket: 'ukruzwa-c52e5.firebasestorage.app',
    iosClientId: '540328794600-4q4je6f9meik1s2h0fm944clk694c9gj.apps.googleusercontent.com',
    iosBundleId: 'com.example.ukruzwa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuhd4OAYWfJWVrnDgikaQX2SrFPodYOuY',
    appId: '1:540328794600:ios:82a5db7d4304d578c56c5d',
    messagingSenderId: '540328794600',
    projectId: 'ukruzwa-c52e5',
    storageBucket: 'ukruzwa-c52e5.firebasestorage.app',
    iosClientId: '540328794600-4q4je6f9meik1s2h0fm944clk694c9gj.apps.googleusercontent.com',
    iosBundleId: 'com.example.ukruzwa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPqCIJeISpHtrI0LioVrORxh9HwltJtl8',
    appId: '1:540328794600:web:d72365e6a3349483c56c5d',
    messagingSenderId: '540328794600',
    projectId: 'ukruzwa-c52e5',
    authDomain: 'ukruzwa-c52e5.firebaseapp.com',
    storageBucket: 'ukruzwa-c52e5.firebasestorage.app',
    measurementId: 'G-RJ15PNKGJT',
  );

}